MAIN_TOKEN = 'MTA4MzEyMjQ1ODkxMzE0NDg4Mw.Gb6MqV.XWf2KjP-3Sj75QIjMX9W_3SkJoWZ11-q5ZhV78'
TEST_TOKEN = 'MTA4MzM5NjE1NDQ2Njc2Mjc4Mg.GRQMjk.maxDv79YYhsIY6nnytvwodrxLnUqcEXipTOF0s'
PREFIX = '.'

CHARACTER_ROLES = ["Alisa Main", "Alisa Sub", "Guest"]
REGION_ROLES = ["NA-EAST", "NA-WEST", "EU-EAST", "EU-WEST", "OCE", "EAST-ASIA", "SEA", "MEA"]
PLATFORM_ROLES = ["PC", "PS4", "XBOX"]
MISC_ROLES = ["Guest", "Streamer"]

VALID_ROLES = CHARACTER_ROLES + REGION_ROLES + PLATFORM_ROLES + MISC_ROLES

ROLES_CHANNEL = 1083761874979532901